name: Dispatch remote Selenium workflow hello test

on:
  push:
    branches: [ main ]

jobs:
  trigger-remote-workflow:
    name: Trigger workflow in other repo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote workflow via workflow-dispatch
        env:
          GH_TOKEN: ${{ secrets.REPO_TRIGGER_PAT }}
        run: |
          gh workflow run run-selenium-tests.yml \
            --repo sharmarishiksh01/WebAppAutomationSG \
            --ref main

      - name: Confirm dispatch
        run: echo "Dispatch request sent to sharmarishiksh01/WebAppAutomationSG/.github/workflows/run-selenium-tests.yml on ref 'main'"

# Notes:
# - Create a Personal Access Token (PAT) with appropriate scopes and add it to this repo's
#   Secrets as `REPO_TRIGGER_PAT`.
#   Recommended scopes: `repo` (or `public_repo` for a public repo) and `workflow` if present.
# - The target workflow must include `workflow_dispatch:` in its `on:` block to be triggerable.
# - This workflow uses GitHub CLI (gh) to trigger the remote workflow_dispatch event.
# - The GH_TOKEN environment variable authenticates the gh CLI with the PAT.



