on:
  push:
    branches: [ main ]

jobs:
  trigger-remote-workflow:
    name: Trigger workflow in other repo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote workflow via workflow-dispatch
        env:
          GH_TOKEN: ${{ secrets.REPO_TRIGGER_PAT }}
        run: |
          gh workflow run run-selenium-tests.yml \
            --repo sharmarishiksh01/WebAppAutomationSG \
            --ref main

      - name: Confirm dispatch
        run: echo "Dispatch request sent to sharmarishiksh01/WebAppAutomationSG/.github/workflows/run-selenium-tests.yml on ref 'main'"
